package com.junar.searchpharma;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CACHE_CONTROL.
 */
public class CacheControl {

    private Long id;
    private java.util.Date lastUpdate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CacheControl() {
    }

    public CacheControl(Long id) {
        this.id = id;
    }

    public CacheControl(Long id, java.util.Date lastUpdate) {
        this.id = id;
        this.lastUpdate = lastUpdate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(java.util.Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
