package com.junar.searchpharma;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COMMUNE.
 */
public class Commune {

    private Long id;
    private Integer code;
    private Integer regionCode;
    private String name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Commune() {
    }

    public Commune(Long id) {
        this.id = id;
    }

    public Commune(Long id, Integer code, Integer regionCode, String name) {
        this.id = id;
        this.code = code;
        this.regionCode = regionCode;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public Integer getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(Integer regionCode) {
        this.regionCode = regionCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return name;
    }
    // KEEP METHODS END

}
