package com.junar.searchpharma;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table COMPLAINT.
 */
public class Complaint {

    private Long id;
    private String comment;
    private String photo;
    private Long latitude;
    private Long longitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Complaint() {
    }

    public Complaint(Long id) {
        this.id = id;
    }

    public Complaint(Long id, String comment, String photo, Long latitude,
            Long longitude) {
        this.id = id;
        this.comment = comment;
        this.photo = photo;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public Long getLatitude() {
        return latitude;
    }

    public void setLatitude(Long latitude) {
        this.latitude = latitude;
    }

    public Long getLongitude() {
        return longitude;
    }

    public void setLongitude(Long longitude) {
        this.longitude = longitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
