package com.junar.searchpharma;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PHARMACY.
 */
public class Pharmacy {

    private Long id;
    private String name;
    private String region;
    private String commune;
    private String address;
    private Integer day;
    private Integer month;
    private String phone;
    private Float latitude;
    private Float longitude;
    private String photo;
    private String schedule;
    private float distance;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public float getDistance() {
        return distance;
    }

    public void setDistance(float distance) {
        this.distance = distance;
    }

    public Pharmacy() {
    }

    public Pharmacy(Long id) {
        this.id = id;
    }

    public Pharmacy(Long id, String name, String region, String commune,
            String address, Integer day, Integer month, String phone,
            Float latitude, Float longitude, String photo, String schedule) {
        this.id = id;
        this.name = name;
        this.region = region;
        this.commune = commune;
        this.address = address;
        this.day = day;
        this.month = month;
        this.phone = phone;
        this.latitude = latitude;
        this.longitude = longitude;
        this.photo = photo;
        this.schedule = schedule;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getCommune() {
        return commune;
    }

    public void setCommune(String commune) {
        this.commune = commune;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getDay() {
        return day;
    }

    public void setDay(Integer day) {
        this.day = day;
    }

    public Integer getMonth() {
        return month;
    }

    public void setMonth(Integer month) {
        this.month = month;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Float getLatitude() {
        return latitude;
    }

    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    public Float getLongitude() {
        return longitude;
    }

    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSchedule() {
        return schedule;
    }

    public void setSchedule(String schedule) {
        this.schedule = schedule;
    }

    // KEEP METHODS - put your custom methods here
    public String toString() {
        return getName().concat(
                getAddress().concat(" - ").concat(this.getCommune())
                        .concat("\n").concat(this.getSchedule()));
    }
    // KEEP METHODS END

}
