package com.junar.searchpharma;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COMMUNE.
 */
public class Commune {

    private Long id;
    private Integer code;
    private Integer regionCode;
    private String name;

    public Commune() {
    }

    public Commune(Long id) {
        this.id = id;
    }

    public Commune(Long id, Integer code, Integer regionCode, String name) {
        this.id = id;
        this.code = code;
        this.regionCode = regionCode;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    public Integer getRegionCode() {
        return regionCode;
    }

    public void setRegionCode(Integer regionCode) {
        this.regionCode = regionCode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
