package com.junar.searchpharma;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table PHARMACY.
 */
public class Pharmacy {

    private Long id;
    private String name;
    private String region;
    private String commune;
    private String address;
    private String phone;
    private Long latitude;
    private Long longitude;
    private String photo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Pharmacy() {
    }

    public Pharmacy(Long id) {
        this.id = id;
    }

    public Pharmacy(Long id, String name, String region, String commune, String address, String phone, Long latitude, Long longitude, String photo) {
        this.id = id;
        this.name = name;
        this.region = region;
        this.commune = commune;
        this.address = address;
        this.phone = phone;
        this.latitude = latitude;
        this.longitude = longitude;
        this.photo = photo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getCommune() {
        return commune;
    }

    public void setCommune(String commune) {
        this.commune = commune;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Long getLatitude() {
        return latitude;
    }

    public void setLatitude(Long latitude) {
        this.latitude = latitude;
    }

    public Long getLongitude() {
        return longitude;
    }

    public void setLongitude(Long longitude) {
        this.longitude = longitude;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
